# Generated by Django 3.2.12 on 2022-04-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='category1',
            new_name='euipment_group',
        ),
    ]
