# Generated by Django 3.2.12 on 2022-04-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsmarket', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EuipGroup',
            new_name='EquipGroup',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='euipment_group',
            new_name='equipment_group',
        ),
    ]
