# Generated by Django 3.2.12 on 2022-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branches',
            field=models.ManyToManyField(blank=True, to='users.Branch'),
        ),
    ]
