# Generated by Django 3.2.12 on 2022-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_company_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_equips',
            field=models.ManyToManyField(blank=True, to='users.Equipment', verbose_name='equipment'),
        ),
    ]
