# Generated by Django 3.2.12 on 2022-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_category1_equipment_euipment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
