# Generated by Django 3.2.12 on 2022-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='attach',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Attachment'),
        ),
    ]
