# Generated by Django 3.2.12 on 2022-05-09 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20220421_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='writer',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='writer'),
        ),
    ]
