# Generated by Django 3.2.12 on 2022-04-18 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialMakerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='official company name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='stock name')),
                ('model_name', models.CharField(max_length=30, verbose_name='model')),
                ('spec', models.CharField(blank=True, max_length=30, verbose_name='specification')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualpools.officialmakername', verbose_name='manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('num_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='num of stocks')),
                ('place', models.CharField(max_length=30, verbose_name='using place')),
                ('new_part', models.BooleanField(verbose_name='new part')),
                ('contact_person', models.CharField(blank=True, max_length=20, verbose_name='person in charge')),
                ('contact_info', models.CharField(blank=True, max_length=30, verbose_name='contact information')),
                ('my_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualpools.stock')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OldMakerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='old manufacturer name')),
                ('official_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualpools.officialmakername')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
