# Generated by Django 3.2.12 on 2022-04-02 12:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialMakerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherMakerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stock_name', models.CharField(max_length=140)),
                ('model_name', models.CharField(max_length=140)),
                ('spec', models.CharField(blank=True, max_length=180)),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualpools.officialmakername')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('num_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('place', models.CharField(max_length=80)),
                ('new_part', models.BooleanField()),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=100)),
                ('my_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualpools.stock')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='officialmakername',
            name='other_names',
            field=models.ManyToManyField(blank=True, to='virtualpools.OtherMakerName'),
        ),
    ]
