# Generated by Django 3.2.12 on 2022-04-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherName',
            new_name='OtherMakerName',
        ),
    ]
