# Generated by Django 3.2.12 on 2022-04-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='new_part',
            new_name='is_new',
        ),
    ]
