# Generated by Django 3.2.12 on 2022-04-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpools', '0002_rename_new_part_stockinfo_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='name',
        ),
    ]
