# Generated by Django 3.2.12 on 2022-04-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpools', '0002_rename_othername_othermakername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='used',
            new_name='new_part',
        ),
        migrations.AlterField(
            model_name='stock',
            name='spec',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
