# Generated by Django 3.2.12 on 2022-04-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpools', '0003_auto_20220402_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='stock_name',
        ),
    ]
