# Generated by Django 3.2.12 on 2022-04-18 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualpools', '0002_rename_new_part_stockinfo_is_new'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('partsmarkets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_part',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='contact_info',
            field=models.CharField(blank=True, max_length=30, verbose_name='contact information'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='new part'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.equipgroup', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact_person',
            field=models.CharField(blank=True, max_length=20, verbose_name='person in charge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualpools.officialmakername', verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=30, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_product',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='number of products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False, verbose_name='on sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec',
            field=models.CharField(blank=True, max_length=30, verbose_name='specification'),
        ),
    ]
