# Generated by Django 3.2.12 on 2022-04-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partsmarkets', '0003_alter_photo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsmarkets.product'),
        ),
    ]
